# Generated by Django 3.2.8 on 2021-11-25 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict', models.ImageField(upload_to=main.models.movie_dir_path_uuid)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(default=datetime.datetime(2021, 11, 25, 14, 44, 11, 657804, tzinfo=utc))),
                ('died', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('value', models.SmallAutoField(choices=[(1, '+'), (-1, '-')], primary_key=True, serialize=False)),
                ('vote_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('year', 'title')},
        ),
        migrations.AddField(
            model_name='movie',
            name='preview',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'WR - Without rating'), (1, 'RW - World rated'), (2, 'R18 - 18+ rated'), (3, 'RL - Limit rated')], default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roles',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.movie'),
        ),
        migrations.AddField(
            model_name='roles',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.person'),
        ),
        migrations.AddField(
            model_name='moviepicture',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AddField(
            model_name='moviepicture',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='actor', through='main.Roles', to='main.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed', to='main.person'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('movie', 'person', 'name')},
        ),
    ]
