# Generated by Django 3.2.8 on 2021-12-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211130_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.RenameField(
            model_name='moviepicture',
            old_name='usr',
            new_name='user',
        ),
    ]
