# Generated by Django 3.2.8 on 2021-12-01 13:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepicture',
            name='pict',
            field=models.ImageField(upload_to=main.models.movie_dir_path_uuid),
        ),
    ]
