# Generated by Django 3.2.8 on 2021-12-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_moviepicture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.TextField(max_length=250, verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=1998, verbose_name='Год выпуска'),
        ),
    ]
