# Generated by Django 3.2.8 on 2021-12-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211204_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.TextField(max_length=10000, verbose_name='Описание фильма'),
        ),
    ]
