# Generated by Django 3.2.8 on 2021-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_movie_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.TextField(max_length=5000, verbose_name='Описание фильма'),
        ),
    ]
