# Generated by Django 3.2.8 on 2021-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_movie_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'WR - Without rating'), (1, 'RW - World rated'), (2, 'R18 - 18+ rated'), (3, 'RL - Limit rated')], default=0, verbose_name='Рейтинг фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(default=10, verbose_name='Длительность'),
        ),
    ]
