# Generated by Django 3.2.8 on 2021-12-18 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20211206_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Название фильма'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='main.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.TextField(db_index=True, max_length=5000, verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='moviepicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_picture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
