# Generated by Django 3.2.8 on 2021-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211218_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Жанр фильма'),
        ),
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('movie', 'person', 'title')},
        ),
    ]
