# Generated by Django 3.2.8 on 2021-12-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20211109_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.myuser', verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
