# Generated by Django 3.2.8 on 2021-12-24 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20211224_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 19, 19, 23, 356830, tzinfo=utc)),
        ),
    ]
