# Generated by Django 3.2.8 on 2021-12-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
