# Generated by Django 3.2.8 on 2021-12-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
