# Generated by Django 3.2.8 on 2021-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateTimeField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='E-mail адрес'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=250, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
