# Generated by Django 3.2.8 on 2021-12-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20211225_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='name',
        ),
    ]
