# Generated by Django 3.2.11 on 2022-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_rename_username_myuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Уведомлен'),
        ),
    ]
