# Generated by Django 3.2.11 on 2022-01-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_myuser_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_notified',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Уведомлен?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.myuser', verbose_name='Пользователь')),
            ],
        ),
    ]
