# Generated by Django 3.2.11 on 2022-01-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20220122_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
